// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFE6P0GHVGcC5VBjwg32eyZrhLp1JmKBg',
    appId: '1:678391264155:web:b0b4faa4233837034de73e',
    messagingSenderId: '678391264155',
    projectId: 'astt-e-sport',
    authDomain: 'astt-e-sport.firebaseapp.com',
    storageBucket: 'astt-e-sport.firebasestorage.app',
    measurementId: 'G-B9G0G0DM01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmJC83QT8AQMV3wbSwL2GpAdXUQiu6OYw',
    appId: '1:678391264155:android:642a175cb12ac0614de73e',
    messagingSenderId: '678391264155',
    projectId: 'astt-e-sport',
    storageBucket: 'astt-e-sport.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDofIWi8ns89o037ojbgmw2CyWzlSbFblo',
    appId: '1:678391264155:ios:7229a9258220ef834de73e',
    messagingSenderId: '678391264155',
    projectId: 'astt-e-sport',
    storageBucket: 'astt-e-sport.firebasestorage.app',
    iosBundleId: 'com.asttesport.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDofIWi8ns89o037ojbgmw2CyWzlSbFblo',
    appId: '1:678391264155:ios:7229a9258220ef834de73e',
    messagingSenderId: '678391264155',
    projectId: 'astt-e-sport',
    storageBucket: 'astt-e-sport.firebasestorage.app',
    iosBundleId: 'com.asttesport.application',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFE6P0GHVGcC5VBjwg32eyZrhLp1JmKBg',
    appId: '1:678391264155:web:575c80f798abb9294de73e',
    messagingSenderId: '678391264155',
    projectId: 'astt-e-sport',
    authDomain: 'astt-e-sport.firebaseapp.com',
    storageBucket: 'astt-e-sport.firebasestorage.app',
    measurementId: 'G-53FXN672Z1',
  );
}
